/* This file was automatically generated by CasADi 3.6.3+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) indy7_M_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

/* M:(i0[6])->(o0[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a7, a8, a9;
  a0=6.0031470000000003e-02;
  a1=2.2204460492503131e-16;
  a2=arg[0]? arg[0][1] : 0;
  a3=sin(a2);
  a4=(a1*a3);
  a2=cos(a2);
  a4=(a4-a2);
  a5=3.5997429999999997e-02;
  a6=1.6172099999999995e-02;
  a7=2.7988909999999999e-02;
  a8=1.1052970000000002e-02;
  a9=4.2108170610702356e-04;
  a10=2.0663085315856589e-04;
  a11=arg[0]? arg[0][5] : 0;
  a12=cos(a11);
  a13=(a10*a12);
  a14=3.6859510095397388e-22;
  a15=-3.3999996207092593e-07;
  a11=sin(a11);
  a16=(a15*a11);
  a16=(a14-a16);
  a13=(a13+a16);
  a16=(a13*a12);
  a17=(a15*a12);
  a18=-2.2559792249945241e-21;
  a19=2.1445085294845767e-04;
  a20=(a19*a11);
  a20=(a18-a20);
  a17=(a17+a20);
  a20=(a17*a11);
  a16=(a16-a20);
  a9=(a9-a16);
  a20=(a15*a12);
  a14=(a14-a20);
  a10=(a10*a11);
  a14=(a14-a10);
  a10=(a14*a11);
  a19=(a19*a12);
  a18=(a18-a19);
  a15=(a15*a11);
  a18=(a18-a15);
  a15=(a18*a12);
  a10=(a10+a15);
  a9=(a9+a10);
  a15=5.8419000022338300e-04;
  a9=(a9+a15);
  a8=(a8+a9);
  a9=3.2640797086459566e-01;
  a19=-2.3113999999999996e-04;
  a20=8.1469787034552752e-05;
  a21=(a20*a12);
  a22=6.8369857227762256e-18;
  a23=-4.6555878300977510e-04;
  a24=(a23*a11);
  a24=(a22-a24);
  a21=(a21+a24);
  a19=(a19-a21);
  a24=casadi_sq(a19);
  a25=6.4458919999999975e-02;
  a26=6.9000000000000006e-02;
  a27=(a23*a12);
  a22=(a22-a27);
  a27=(a20*a11);
  a22=(a22-a27);
  a22=(a26+a22);
  a25=(a25-a22);
  a27=casadi_sq(a25);
  a24=(a24+a27);
  a24=(a9*a24);
  a8=(a8+a24);
  a24=2.7547950000000002e-02;
  a10=(a15-a10);
  a24=(a24+a10);
  a10=-9.7962319999999978e-02;
  a27=-1.6800000000000001e-01;
  a28=(a1*a12);
  a29=-2.2204460492503131e-16;
  a30=(a29*a11);
  a28=(a28+a30);
  a20=(a20*a28);
  a30=(a29*a12);
  a31=(a1*a11);
  a30=(a30-a31);
  a23=(a23*a30);
  a31=-3.0791046353432411e-02;
  a23=(a23+a31);
  a20=(a20+a23);
  a20=(a27+a20);
  a10=(a10-a20);
  a23=casadi_sq(a10);
  a31=casadi_sq(a19);
  a23=(a23+a31);
  a23=(a9*a23);
  a24=(a24+a23);
  a8=(a8-a24);
  a23=3.6982910000000001e-02;
  a16=(a16+a15);
  a23=(a23+a16);
  a16=casadi_sq(a10);
  a15=casadi_sq(a25);
  a16=(a16+a15);
  a16=(a9*a16);
  a23=(a23+a16);
  a23=(a23-a24);
  a16=(a8+a23);
  a15=arg[0]? arg[0][4] : 0;
  a31=sin(a15);
  a32=(a1*a31);
  a33=(a32*a8);
  a15=cos(a15);
  a34=(a1*a15);
  a35=5.5170000000000002e-05;
  a13=(a13*a28);
  a17=(a17*a30);
  a13=(a13+a17);
  a17=-5.0800135985204594e-06;
  a36=(a17*a11);
  a37=8.3000237965345357e-07;
  a38=(a37*a12);
  a36=(a36-a38);
  a13=(a13+a36);
  a35=(a35+a13);
  a13=(a9*a10);
  a13=(a13*a19);
  a35=(a35-a13);
  a13=(a34*a35);
  a36=2.;
  a38=-1.4819769999999999e-02;
  a39=(a14*a28);
  a40=(a18*a30);
  a39=(a39+a40);
  a40=(a17*a12);
  a41=(a37*a11);
  a40=(a40+a41);
  a39=(a39+a40);
  a38=(a38+a39);
  a10=(a9*a10);
  a10=(a10*a25);
  a38=(a38-a10);
  a10=(a36*a38);
  a13=(a13-a10);
  a33=(a33+a13);
  a13=(a33*a32);
  a10=(a32*a35);
  a39=(a34*a23);
  a40=-3.7400000000000001e-05;
  a14=(a14*a12);
  a18=(a18*a11);
  a14=(a14-a18);
  a37=(a37*a30);
  a17=(a17*a28);
  a37=(a37-a17);
  a14=(a14+a37);
  a40=(a40+a14);
  a9=(a9*a19);
  a9=(a9*a25);
  a40=(a40-a9);
  a9=(a40+a40);
  a39=(a39-a9);
  a10=(a10+a39);
  a39=(a10*a34);
  a13=(a13+a39);
  a16=(a16-a13);
  a39=(a1*a31);
  a39=(a39-a15);
  a8=(a39*a8);
  a9=(a1*a15);
  a9=(a31+a9);
  a25=(a9*a35);
  a8=(a8+a25);
  a25=(a8*a39);
  a35=(a39*a35);
  a23=(a9*a23);
  a35=(a35+a23);
  a23=(a35*a9);
  a25=(a25+a23);
  a16=(a16-a25);
  a16=(a16+a24);
  a7=(a7+a16);
  a16=1.1721375639086467e+00;
  a23=-7.0984400000000003e-02;
  a19=-1.1400000000000000e-01;
  a14=-8.3585558345339220e-02;
  a37=1.4675807652024542e-01;
  a20=(a37*a20);
  a14=(a14+a20);
  a20=(a32*a14);
  a17=-1.9721833819311043e-04;
  a21=(a37*a21);
  a17=(a17+a21);
  a21=(a34*a17);
  a18=5.4999052886227598e-02;
  a37=(a37*a22);
  a18=(a18+a37);
  a21=(a21-a18);
  a20=(a20+a21);
  a20=(a19+a20);
  a23=(a23-a20);
  a21=casadi_sq(a23);
  a37=7.6491279999999995e-02;
  a22=8.3000000000000004e-02;
  a41=(a39*a14);
  a42=(a9*a17);
  a41=(a41+a42);
  a41=(a22+a41);
  a37=(a37-a41);
  a42=casadi_sq(a37);
  a21=(a21+a42);
  a21=(a16*a21);
  a7=(a7+a21);
  a21=1.4962110000000001e-02;
  a25=(a25+a24);
  a21=(a21+a25);
  a25=-2.6846999999999998e-04;
  a42=(a1*a15);
  a42=(a42+a31);
  a43=(a42*a14);
  a31=(a1*a31);
  a15=(a15-a31);
  a31=(a15*a17);
  a44=(a1*a18);
  a31=(a31+a44);
  a43=(a43+a31);
  a25=(a25-a43);
  a31=casadi_sq(a25);
  a44=casadi_sq(a23);
  a31=(a31+a44);
  a31=(a16*a31);
  a21=(a21+a31);
  a7=(a7-a21);
  a31=1.4430760000000001e-02;
  a13=(a13+a24);
  a31=(a31+a13);
  a13=casadi_sq(a25);
  a44=casadi_sq(a37);
  a13=(a13+a44);
  a13=(a16*a13);
  a31=(a31+a13);
  a31=(a31-a21);
  a13=(a7+a31);
  a44=arg[0]? arg[0][3] : 0;
  a45=cos(a44);
  a46=(a45*a7);
  a47=-4.7679999999999998e-05;
  a48=(a8*a42);
  a49=(a35*a15);
  a48=(a48+a49);
  a49=(a34*a38);
  a50=(a32*a40);
  a49=(a49-a50);
  a48=(a48-a49);
  a47=(a47+a48);
  a48=(a16*a25);
  a48=(a48*a37);
  a47=(a47-a48);
  a48=(a36*a47);
  a49=(a1*a48);
  a44=sin(a44);
  a50=3.8930000000000002e-05;
  a33=(a33*a42);
  a10=(a10*a15);
  a33=(a33+a10);
  a10=(a9*a38);
  a51=(a39*a40);
  a10=(a10-a51);
  a33=(a33+a10);
  a50=(a50+a33);
  a25=(a16*a25);
  a25=(a25*a23);
  a50=(a50-a25);
  a25=(a44*a50);
  a49=(a49-a25);
  a46=(a46+a49);
  a49=(a46*a45);
  a25=(a45*a50);
  a33=-1.2662959999999999e-02;
  a8=(a8*a32);
  a35=(a35*a34);
  a8=(a8+a35);
  a35=(a15*a38);
  a10=(a42*a40);
  a35=(a35-a10);
  a8=(a8+a35);
  a33=(a33+a8);
  a16=(a16*a23);
  a16=(a16*a37);
  a33=(a33-a16);
  a16=(a33+a33);
  a37=(a1*a16);
  a23=(a44*a31);
  a37=(a37-a23);
  a25=(a25+a37);
  a37=(a25*a44);
  a49=(a49-a37);
  a13=(a13-a49);
  a48=(a1*a48);
  a37=(a45*a50);
  a48=(a48-a37);
  a7=(a44*a7);
  a48=(a48-a7);
  a7=(a48*a44);
  a16=(a1*a16);
  a31=(a45*a31);
  a16=(a16-a31);
  a50=(a44*a50);
  a16=(a16-a50);
  a50=(a16*a45);
  a7=(a7+a50);
  a13=(a13+a7);
  a13=(a13+a21);
  a6=(a6+a13);
  a13=1.7124110941795541e+00;
  a50=2.1420999999999994e-04;
  a31=-1.2072237989225459e-04;
  a37=5.5033195555460734e-01;
  a43=(a37*a43);
  a31=(a31+a43);
  a43=(a45*a31);
  a23=3.4395684294724983e-02;
  a41=(a37*a41);
  a23=(a23+a41);
  a41=(a1*a23);
  a8=-3.1919416334129543e-02;
  a37=(a37*a20);
  a8=(a8+a37);
  a37=(a44*a8);
  a41=(a41-a37);
  a43=(a43+a41);
  a50=(a50-a43);
  a41=casadi_sq(a50);
  a37=-7.0003829999999975e-02;
  a20=-7.4999999999999997e-02;
  a35=(a1*a23);
  a10=(a45*a8);
  a35=(a35-a10);
  a10=(a44*a31);
  a35=(a35-a10);
  a35=(a20+a35);
  a37=(a37-a35);
  a10=casadi_sq(a37);
  a41=(a41+a10);
  a41=(a13*a41);
  a6=(a6+a41);
  a41=1.0022522000000000e-01;
  a7=(a21-a7);
  a41=(a41+a7);
  a7=-1.6804015999999994e-01;
  a10=-2.6700000000000002e-01;
  a51=(a1*a45);
  a52=(a29*a44);
  a51=(a51+a52);
  a52=(a51*a31);
  a29=(a29*a45);
  a53=(a1*a44);
  a29=(a29-a53);
  a53=(a29*a8);
  a53=(a53-a23);
  a52=(a52+a53);
  a52=(a10+a52);
  a7=(a7-a52);
  a53=casadi_sq(a7);
  a54=casadi_sq(a50);
  a53=(a53+a54);
  a53=(a13*a53);
  a41=(a41+a53);
  a6=(a6-a41);
  a53=1.1364055000000001e-01;
  a49=(a49+a21);
  a53=(a53+a49);
  a49=casadi_sq(a7);
  a54=casadi_sq(a37);
  a49=(a49+a54);
  a49=(a13*a49);
  a53=(a53+a49);
  a53=(a53-a41);
  a49=(a6+a53);
  a54=arg[0]? arg[0][2] : 0;
  a55=sin(a54);
  a6=(a55*a6);
  a54=cos(a54);
  a56=-1.1817000000000000e-04;
  a46=(a46*a51);
  a25=(a25*a29);
  a46=(a46+a25);
  a25=(a44*a33);
  a57=(a45*a47);
  a25=(a25-a57);
  a46=(a46+a25);
  a56=(a56+a46);
  a46=(a13*a7);
  a46=(a46*a50);
  a56=(a56-a46);
  a46=(a54*a56);
  a6=(a6+a46);
  a46=(a6*a55);
  a56=(a55*a56);
  a53=(a54*a53);
  a56=(a56+a53);
  a53=(a56*a54);
  a46=(a46+a53);
  a49=(a49-a46);
  a49=(a49+a41);
  a5=(a5+a49);
  a49=3.2700619797990886e+00;
  a53=-2.3609999999999999e-05;
  a25=-6.0751819848336858e-02;
  a57=6.3846844796900415e-01;
  a52=(a57*a52);
  a25=(a25+a52);
  a52=(a55*a25);
  a58=7.7443673760559616e-05;
  a43=(a57*a43);
  a58=(a58+a43);
  a43=(a54*a58);
  a52=(a52+a43);
  a53=(a53-a52);
  a43=casadi_sq(a53);
  a59=4.7625540000000001e-02;
  a60=-3.0499999999999999e-02;
  a61=-2.5308593308013983e-02;
  a57=(a57*a35);
  a61=(a61+a57);
  a57=(a60+a61);
  a59=(a59-a57);
  a35=casadi_sq(a59);
  a43=(a43+a35);
  a43=(a49*a43);
  a5=(a5+a43);
  a43=7.0024118999999996e-01;
  a43=(a43+a41);
  a35=-2.9477535999999999e-01;
  a62=-4.5000000000000001e-01;
  a63=(a54*a25);
  a64=(a55*a58);
  a63=(a63-a64);
  a63=(a62+a63);
  a35=(a35-a63);
  a64=casadi_sq(a35);
  a65=casadi_sq(a53);
  a64=(a64+a65);
  a64=(a49*a64);
  a43=(a43+a64);
  a5=(a5-a43);
  a5=(a4*a5);
  a64=(a1*a2);
  a64=(a3+a64);
  a65=-4.6930000000000000e-05;
  a6=(a6*a54);
  a56=(a56*a55);
  a6=(a6-a56);
  a65=(a65+a6);
  a6=(a49*a35);
  a6=(a6*a53);
  a65=(a65-a6);
  a6=(a64*a65);
  a5=(a5+a6);
  a5=(a5*a4);
  a65=(a4*a65);
  a6=7.2293306000000002e-01;
  a46=(a46+a41);
  a6=(a6+a46);
  a46=casadi_sq(a35);
  a56=casadi_sq(a59);
  a46=(a46+a56);
  a46=(a49*a46);
  a6=(a6+a46);
  a6=(a6-a43);
  a6=(a64*a6);
  a65=(a65+a6);
  a65=(a65*a64);
  a5=(a5+a65);
  a5=(a5+a43);
  a0=(a0+a5);
  a5=6.1441004554871421e+00;
  a65=-2.3749000000000000e-04;
  a6=(a1*a2);
  a6=(a6+a3);
  a46=-1.2993458852078907e-01;
  a56=5.5920810843623758e-01;
  a63=(a56*a63);
  a46=(a46+a63);
  a63=(a6*a46);
  a66=(a1*a3);
  a66=(a2-a66);
  a67=-1.0407096559820434e-05;
  a52=(a56*a52);
  a67=(a67+a52);
  a52=(a66*a67);
  a68=2.0992951863345637e-02;
  a56=(a56*a57);
  a68=(a68+a56);
  a56=(a1*a68);
  a52=(a52+a56);
  a63=(a63+a52);
  a65=(a65-a63);
  a65=casadi_sq(a65);
  a52=-4.3103130000000003e-02;
  a56=-1.0900000000000000e-01;
  a3=(a1*a3);
  a3=(a3*a46);
  a2=(a1*a2);
  a2=(a2*a67);
  a2=(a2-a68);
  a3=(a3+a2);
  a3=(a56+a3);
  a52=(a52-a3);
  a52=casadi_sq(a52);
  a65=(a65+a52);
  a5=(a5*a65);
  a0=(a0+a5);
  a5=2.4710718260000000e+01;
  a65=-1.0999038140348657e-04;
  a52=5.3686310411601923e-01;
  a63=(a52*a63);
  a65=(a65+a63);
  a65=casadi_sq(a65);
  a63=-1.9962649831083683e-02;
  a52=(a52*a3);
  a63=(a63+a52);
  a63=casadi_sq(a63);
  a65=(a65+a63);
  a5=(a5*a65);
  a0=(a0+a5);
  if (res[0]!=0) res[0][0]=a0;
  a0=-5.2403459999999999e-02;
  a5=3.3418820000000002e-02;
  a65=(a48*a51);
  a63=(a16*a29);
  a65=(a65+a63);
  a63=(a45*a33);
  a52=(a44*a47);
  a63=(a63+a52);
  a65=(a65+a63);
  a5=(a5+a65);
  a7=(a13*a7);
  a7=(a7*a37);
  a5=(a5-a7);
  a36=(a36*a5);
  a7=(a36*a54);
  a65=-4.3710000000000000e-05;
  a48=(a48*a45);
  a16=(a16*a44);
  a48=(a48-a16);
  a16=(a29*a47);
  a63=(a51*a33);
  a16=(a16-a63);
  a48=(a48+a16);
  a65=(a65+a48);
  a13=(a13*a50);
  a13=(a13*a37);
  a65=(a65-a13);
  a13=(a65+a65);
  a37=(a13*a55);
  a7=(a7-a37);
  a37=(a54*a5);
  a50=(a55*a65);
  a37=(a37-a50);
  a7=(a7-a37);
  a0=(a0+a7);
  a35=(a49*a35);
  a35=(a35*a59);
  a0=(a0-a35);
  a35=1.3266272909999998e+01;
  a7=(a35*a46);
  a7=(a7*a68);
  a0=(a0-a7);
  a0=(a4*a0);
  a7=1.7600000000000001e-06;
  a36=(a36*a55);
  a13=(a13*a54);
  a36=(a36+a13);
  a13=(a54*a65);
  a37=(a55*a5);
  a13=(a13+a37);
  a36=(a36-a13);
  a7=(a7+a36);
  a49=(a49*a53);
  a49=(a49*a59);
  a7=(a7-a49);
  a49=(a35*a67);
  a49=(a49*a68);
  a7=(a7-a49);
  a7=(a64*a7);
  a0=(a0+a7);
  a7=-1.3266272909999998e+01;
  a7=(a7*a67);
  a7=(a6*a7);
  a49=(a35*a46);
  a49=(a66*a49);
  a7=(a7+a49);
  a7=(a56*a7);
  a0=(a0-a7);
  if (res[0]!=0) res[0][1]=a0;
  a7=7.4186073799999992e+00;
  a49=(a7*a25);
  a49=(a49*a61);
  a5=(a5-a49);
  a49=(a54*a5);
  a68=(a7*a58);
  a68=(a68*a61);
  a65=(a65-a68);
  a68=(a55*a65);
  a49=(a49-a68);
  a68=-7.4186073799999992e+00;
  a68=(a68*a58);
  a61=(a55*a68);
  a59=(a7*a25);
  a53=(a54*a59);
  a61=(a61+a53);
  a53=(a60*a61);
  a49=(a49-a53);
  a49=(a4*a49);
  a5=(a55*a5);
  a65=(a54*a65);
  a5=(a5+a65);
  a68=(a54*a68);
  a59=(a55*a59);
  a68=(a68-a59);
  a59=(a60*a68);
  a5=(a5+a59);
  a5=(a64*a5);
  a49=(a49+a5);
  a68=(a6*a68);
  a5=(a66*a61);
  a68=(a68+a5);
  a68=(a56*a68);
  a49=(a49-a68);
  if (res[0]!=0) res[0][2]=a49;
  a68=4.7365467399999996e+00;
  a5=(a68*a31);
  a5=(a5*a23);
  a47=(a47-a5);
  a5=(a51*a47);
  a59=(a68*a8);
  a59=(a59*a23);
  a33=(a33-a59);
  a59=(a29*a33);
  a23=casadi_sq(a31);
  a65=casadi_sq(a8);
  a23=(a23+a65);
  a23=(a68*a23);
  a21=(a21+a23);
  a59=(a59-a21);
  a5=(a5+a59);
  a59=-4.7365467399999996e+00;
  a59=(a59*a8);
  a8=(a45*a59);
  a68=(a68*a31);
  a31=(a44*a68);
  a8=(a8-a31);
  a31=(a20*a8);
  a5=(a5-a31);
  a31=(a54*a5);
  a23=(a45*a47);
  a65=(a1*a21);
  a53=(a44*a33);
  a65=(a65-a53);
  a23=(a23+a65);
  a65=(a51*a59);
  a53=(a29*a68);
  a65=(a65+a53);
  a53=(a20*a65);
  a59=(a44*a59);
  a68=(a45*a68);
  a59=(a59+a68);
  a68=(a10*a59);
  a53=(a53+a68);
  a23=(a23+a53);
  a53=(a55*a23);
  a31=(a31-a53);
  a53=(a55*a65);
  a68=(a54*a8);
  a53=(a53+a68);
  a68=(a60*a53);
  a31=(a31-a68);
  a31=(a4*a31);
  a5=(a55*a5);
  a23=(a54*a23);
  a5=(a5+a23);
  a65=(a54*a65);
  a23=(a55*a8);
  a65=(a65-a23);
  a23=(a60*a65);
  a68=(a62*a59);
  a23=(a23+a68);
  a5=(a5+a23);
  a5=(a64*a5);
  a31=(a31+a5);
  a65=(a6*a65);
  a5=(a66*a53);
  a59=(a1*a59);
  a5=(a5-a59);
  a65=(a65+a5);
  a65=(a56*a65);
  a31=(a31-a65);
  if (res[0]!=0) res[0][3]=a31;
  a65=2.6066730300000001e+00;
  a5=(a65*a14);
  a5=(a5*a18);
  a38=(a38-a5);
  a5=(a42*a38);
  a59=(a65*a17);
  a59=(a59*a18);
  a40=(a40-a59);
  a59=(a15*a40);
  a18=casadi_sq(a14);
  a23=casadi_sq(a17);
  a18=(a18+a23);
  a18=(a65*a18);
  a24=(a24+a18);
  a18=(a1*a24);
  a59=(a59+a18);
  a5=(a5+a59);
  a59=-2.6066730300000001e+00;
  a59=(a59*a17);
  a17=(a39*a59);
  a65=(a65*a14);
  a14=(a9*a65);
  a17=(a17+a14);
  a14=(a19*a17);
  a18=(a32*a59);
  a23=(a34*a65);
  a18=(a18+a23);
  a23=(a22*a18);
  a14=(a14-a23);
  a5=(a5+a14);
  a14=(a51*a5);
  a23=(a32*a38);
  a68=(a34*a40);
  a68=(a68-a24);
  a23=(a23+a68);
  a59=(a42*a59);
  a65=(a15*a65);
  a59=(a59+a65);
  a65=(a22*a59);
  a23=(a23+a65);
  a65=(a29*a23);
  a38=(a39*a38);
  a40=(a9*a40);
  a38=(a38+a40);
  a40=(a19*a59);
  a38=(a38-a40);
  a65=(a65-a38);
  a14=(a14+a65);
  a65=(a45*a59);
  a40=(a1*a17);
  a68=(a44*a18);
  a40=(a40-a68);
  a65=(a65+a40);
  a40=(a20*a65);
  a14=(a14-a40);
  a40=(a54*a14);
  a68=(a45*a5);
  a36=(a1*a38);
  a13=(a44*a23);
  a36=(a36-a13);
  a68=(a68+a36);
  a36=(a51*a59);
  a13=(a29*a18);
  a13=(a13-a17);
  a36=(a36+a13);
  a13=(a20*a36);
  a17=(a1*a17);
  a18=(a45*a18);
  a17=(a17-a18);
  a59=(a44*a59);
  a17=(a17-a59);
  a59=(a10*a17);
  a13=(a13-a59);
  a68=(a68+a13);
  a13=(a55*a68);
  a40=(a40-a13);
  a13=(a55*a36);
  a59=(a54*a65);
  a13=(a13+a59);
  a59=(a60*a13);
  a40=(a40-a59);
  a40=(a4*a40);
  a14=(a55*a14);
  a68=(a54*a68);
  a14=(a14+a68);
  a36=(a54*a36);
  a68=(a55*a65);
  a36=(a36-a68);
  a68=(a60*a36);
  a59=(a62*a17);
  a68=(a68-a59);
  a14=(a14+a68);
  a14=(a64*a14);
  a40=(a40+a14);
  a36=(a6*a36);
  a14=(a66*a13);
  a17=(a1*a17);
  a14=(a14+a17);
  a36=(a36+a14);
  a36=(a56*a36);
  a40=(a40-a36);
  if (res[0]!=0) res[0][4]=a40;
  a36=-1.2964039586562383e-07;
  a14=(a36*a28);
  a17=4.0386133176874686e-07;
  a68=(a17*a30);
  a59=-5.8427545519626933e-04;
  a68=(a68+a59);
  a14=(a14+a68);
  a68=1.7809966141920004e-04;
  a59=(a68*a12);
  a18=3.1166293100400009e-05;
  a37=(a18*a11);
  a59=(a59-a37);
  a37=(a26*a59);
  a14=(a14-a37);
  a37=(a42*a14);
  a50=(a36*a12);
  a48=1.2973521261644846e-19;
  a16=(a17*a11);
  a16=(a48-a16);
  a50=(a50+a16);
  a28=(a68*a28);
  a30=(a18*a30);
  a28=(a28+a30);
  a26=(a26*a28);
  a68=(a68*a11);
  a18=(a18*a12);
  a68=(a68+a18);
  a18=(a27*a68);
  a26=(a26+a18);
  a50=(a50+a26);
  a26=(a15*a50);
  a17=(a17*a12);
  a48=(a48-a17);
  a36=(a36*a11);
  a48=(a48-a36);
  a27=(a27*a59);
  a48=(a48+a27);
  a27=(a1*a48);
  a26=(a26+a27);
  a37=(a37+a26);
  a26=(a39*a28);
  a27=(a9*a59);
  a26=(a26+a27);
  a27=(a19*a26);
  a36=(a32*a28);
  a11=(a34*a59);
  a11=(a11+a68);
  a36=(a36+a11);
  a11=(a22*a36);
  a27=(a27-a11);
  a37=(a37+a27);
  a27=(a51*a37);
  a32=(a32*a14);
  a34=(a34*a50);
  a34=(a34-a48);
  a32=(a32+a34);
  a42=(a42*a28);
  a15=(a15*a59);
  a68=(a1*a68);
  a15=(a15-a68);
  a42=(a42+a15);
  a22=(a22*a42);
  a32=(a32+a22);
  a22=(a29*a32);
  a39=(a39*a14);
  a9=(a9*a50);
  a39=(a39+a9);
  a19=(a19*a42);
  a39=(a39-a19);
  a22=(a22-a39);
  a27=(a27+a22);
  a22=(a45*a42);
  a19=(a1*a26);
  a9=(a44*a36);
  a19=(a19-a9);
  a22=(a22+a19);
  a19=(a20*a22);
  a27=(a27-a19);
  a19=(a54*a27);
  a9=(a45*a37);
  a50=(a1*a39);
  a14=(a44*a32);
  a50=(a50-a14);
  a9=(a9+a50);
  a51=(a51*a42);
  a29=(a29*a36);
  a29=(a29-a26);
  a51=(a51+a29);
  a20=(a20*a51);
  a26=(a1*a26);
  a36=(a45*a36);
  a26=(a26-a36);
  a42=(a44*a42);
  a26=(a26-a42);
  a42=(a10*a26);
  a20=(a20-a42);
  a9=(a9+a20);
  a20=(a55*a9);
  a19=(a19-a20);
  a20=(a55*a51);
  a42=(a54*a22);
  a20=(a20+a42);
  a42=(a60*a20);
  a19=(a19-a42);
  a4=(a4*a19);
  a27=(a55*a27);
  a9=(a54*a9);
  a27=(a27+a9);
  a54=(a54*a51);
  a55=(a55*a22);
  a54=(a54-a55);
  a60=(a60*a54);
  a55=(a62*a26);
  a60=(a60-a55);
  a27=(a27+a60);
  a64=(a64*a27);
  a4=(a4+a64);
  a6=(a6*a54);
  a66=(a66*a20);
  a26=(a1*a26);
  a66=(a66+a26);
  a6=(a6+a66);
  a56=(a56*a6);
  a4=(a4-a56);
  if (res[0]!=0) res[0][5]=a4;
  if (res[0]!=0) res[0][6]=a0;
  a46=casadi_sq(a46);
  a67=casadi_sq(a67);
  a46=(a46+a67);
  a35=(a35*a46);
  a43=(a43+a35);
  if (res[0]!=0) res[0][7]=a43;
  a25=casadi_sq(a25);
  a58=casadi_sq(a58);
  a25=(a25+a58);
  a7=(a7*a25);
  a41=(a41+a7);
  a61=(a62*a61);
  a61=(a41+a61);
  if (res[0]!=0) res[0][8]=a61;
  a7=(a1*a21);
  a33=(a45*a33);
  a7=(a7-a33);
  a47=(a44*a47);
  a7=(a7-a47);
  a8=(a10*a8);
  a7=(a7+a8);
  a53=(a62*a53);
  a53=(a7+a53);
  if (res[0]!=0) res[0][9]=a53;
  a8=(a1*a38);
  a23=(a45*a23);
  a8=(a8-a23);
  a5=(a44*a5);
  a8=(a8-a5);
  a65=(a10*a65);
  a8=(a8+a65);
  a13=(a62*a13);
  a13=(a8+a13);
  if (res[0]!=0) res[0][10]=a13;
  a1=(a1*a39);
  a45=(a45*a32);
  a1=(a1-a45);
  a44=(a44*a37);
  a1=(a1-a44);
  a10=(a10*a22);
  a1=(a1+a10);
  a62=(a62*a20);
  a62=(a1+a62);
  if (res[0]!=0) res[0][11]=a62;
  if (res[0]!=0) res[0][12]=a49;
  if (res[0]!=0) res[0][13]=a61;
  if (res[0]!=0) res[0][14]=a41;
  if (res[0]!=0) res[0][15]=a7;
  if (res[0]!=0) res[0][16]=a8;
  if (res[0]!=0) res[0][17]=a1;
  if (res[0]!=0) res[0][18]=a31;
  if (res[0]!=0) res[0][19]=a53;
  if (res[0]!=0) res[0][20]=a7;
  if (res[0]!=0) res[0][21]=a21;
  if (res[0]!=0) res[0][22]=a38;
  if (res[0]!=0) res[0][23]=a39;
  if (res[0]!=0) res[0][24]=a40;
  if (res[0]!=0) res[0][25]=a13;
  if (res[0]!=0) res[0][26]=a8;
  if (res[0]!=0) res[0][27]=a38;
  if (res[0]!=0) res[0][28]=a24;
  if (res[0]!=0) res[0][29]=a48;
  if (res[0]!=0) res[0][30]=a4;
  if (res[0]!=0) res[0][31]=a62;
  if (res[0]!=0) res[0][32]=a1;
  if (res[0]!=0) res[0][33]=a39;
  if (res[0]!=0) res[0][34]=a48;
  a48=5.8427545519626933e-04;
  if (res[0]!=0) res[0][35]=a48;
  return 0;
}

CASADI_SYMBOL_EXPORT int M(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int M_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int M_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int M_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_release(int mem) {
}

CASADI_SYMBOL_EXPORT void M_incref(void) {
}

CASADI_SYMBOL_EXPORT void M_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int M_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int M_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real M_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int M_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
