/* This file was automatically generated by CasADi 3.6.3+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) indy7_CoM_x_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};

/* centerOfMass:(q[6])->(CoM Position[3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=cos(a0);
  a2=-2.7179413261715002e-03;
  a3=2.2204460492503131e-16;
  a4=arg[0]? arg[0][1] : 0;
  a5=cos(a4);
  a6=(a3*a5);
  a4=sin(a4);
  a6=(a6+a4);
  a7=-1.7237477117653406e+00;
  a8=arg[0]? arg[0][2] : 0;
  a9=cos(a8);
  a10=-4.5069389907530222e-01;
  a11=arg[0]? arg[0][3] : 0;
  a12=cos(a11);
  a13=(a3*a12);
  a14=-2.2204460492503131e-16;
  a11=sin(a11);
  a15=(a14*a11);
  a13=(a13+a15);
  a15=-5.7180719492369993e-04;
  a16=arg[0]? arg[0][4] : 0;
  a17=cos(a16);
  a18=(a3*a17);
  a16=sin(a16);
  a18=(a18+a16);
  a19=-2.1788022063628715e-01;
  a20=3.1166293100400009e-05;
  a21=arg[0]? arg[0][5] : 0;
  a22=cos(a21);
  a23=(a3*a22);
  a21=sin(a21);
  a24=(a14*a21);
  a23=(a23+a24);
  a23=(a20*a23);
  a24=-1.7809966141920004e-04;
  a25=(a14*a22);
  a26=(a3*a21);
  a25=(a25-a26);
  a25=(a24*a25);
  a26=-1.1779294635640402e-02;
  a25=(a25+a26);
  a23=(a23+a25);
  a25=-6.4268453760000011e-02;
  a23=(a23+a25);
  a19=(a19+a23);
  a18=(a18*a19);
  a23=(a3*a16);
  a23=(a17-a23);
  a25=-5.1408372318939989e-04;
  a26=(a20*a22);
  a27=2.6155288236663137e-18;
  a28=(a24*a21);
  a28=(a27-a28);
  a26=(a26+a28);
  a25=(a25+a26);
  a23=(a23*a25);
  a26=1.4336454783407315e-01;
  a24=(a24*a22);
  a27=(a27-a24);
  a20=(a20*a21);
  a27=(a27-a20);
  a20=2.6395972080000003e-02;
  a27=(a27+a20);
  a26=(a26+a27);
  a27=(a3*a26);
  a23=(a23+a27);
  a18=(a18+a23);
  a15=(a15+a18);
  a13=(a13*a15);
  a14=(a14*a12);
  a18=(a3*a11);
  a14=(a14-a18);
  a18=-1.5118780738012400e-01;
  a23=(a3*a16);
  a23=(a23*a19);
  a27=(a3*a17);
  a27=(a27*a25);
  a27=(a27-a26);
  a23=(a23+a27);
  a27=-2.9716072541999999e-01;
  a23=(a23+a27);
  a18=(a18+a23);
  a14=(a14*a18);
  a23=1.6291676631624880e-01;
  a27=(a3*a16);
  a27=(a27-a17);
  a27=(a27*a19);
  a17=(a3*a17);
  a16=(a16+a17);
  a16=(a16*a25);
  a27=(a27+a16);
  a16=2.1635386149000002e-01;
  a27=(a27+a16);
  a23=(a23+a27);
  a14=(a14-a23);
  a13=(a13+a14);
  a14=-1.2646579795799999e+00;
  a13=(a13+a14);
  a10=(a10+a13);
  a13=(a9*a10);
  a8=sin(a8);
  a14=5.7452420969439984e-04;
  a27=(a12*a15);
  a16=(a3*a23);
  a25=(a11*a18);
  a16=(a16-a25);
  a27=(a27+a16);
  a14=(a14+a27);
  a27=(a8*a14);
  a13=(a13-a27);
  a27=-3.3383733209999997e+00;
  a13=(a13+a27);
  a7=(a7+a13);
  a6=(a6*a7);
  a13=(a3*a4);
  a13=(a5-a13);
  a27=-1.3806338316329998e-04;
  a8=(a8*a10);
  a9=(a9*a14);
  a8=(a8+a9);
  a27=(a27+a8);
  a13=(a13*a27);
  a8=2.7849822860563617e-01;
  a9=-1.8775451709225113e-01;
  a23=(a3*a23);
  a12=(a12*a18);
  a23=(a23-a12);
  a11=(a11*a15);
  a23=(a23-a11);
  a11=-3.5524100549999998e-01;
  a23=(a23+a11);
  a9=(a9+a23);
  a23=-2.2626752508999998e-01;
  a9=(a9+a23);
  a8=(a8+a9);
  a9=(a3*a8);
  a13=(a13+a9);
  a6=(a6+a13);
  a2=(a2+a6);
  a6=(a1*a2);
  a0=sin(a0);
  a13=-4.9329141569894558e-01;
  a9=(a3*a4);
  a9=(a9*a7);
  a23=(a3*a5);
  a23=(a23*a27);
  a23=(a23-a8);
  a9=(a9+a23);
  a23=-1.4460237471899997e+00;
  a9=(a9+a23);
  a13=(a13+a9);
  a9=(a0*a13);
  a6=(a6-a9);
  a9=2.4710718260000000e+01;
  a6=(a6/a9);
  if (res[0]!=0) res[0][0]=a6;
  a0=(a0*a2);
  a1=(a1*a13);
  a0=(a0+a1);
  a0=(a0/a9);
  if (res[0]!=0) res[0][1]=a0;
  a0=1.5158621066110862e+00;
  a1=(a3*a4);
  a1=(a1-a5);
  a1=(a1*a7);
  a3=(a3*a5);
  a4=(a4+a3);
  a4=(a4*a27);
  a1=(a1+a4);
  a4=2.9451125860199996e+00;
  a1=(a1+a4);
  a0=(a0+a1);
  a1=1.9150806651500001e+00;
  a0=(a0+a1);
  a0=(a0/a9);
  if (res[0]!=0) res[0][2]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int centerOfMass(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int centerOfMass_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int centerOfMass_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void centerOfMass_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int centerOfMass_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void centerOfMass_release(int mem) {
}

CASADI_SYMBOL_EXPORT void centerOfMass_incref(void) {
}

CASADI_SYMBOL_EXPORT void centerOfMass_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int centerOfMass_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int centerOfMass_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real centerOfMass_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* centerOfMass_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* centerOfMass_name_out(casadi_int i) {
  switch (i) {
    case 0: return "CoM Position";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* centerOfMass_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* centerOfMass_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int centerOfMass_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
