/*
 * SharedMemoryAddress.h
 *
 *  Created on: 2018. 1. 11.
 *      Author: Hanter Jung
 */

#ifndef NRMKFRAMEWORK_SHAREDMEMORYADDRESS_H_
#define NRMKFRAMEWORK_SHAREDMEMORYADDRESS_H_

/*** Size Information of Shared Memory ***/
#define NRMK_SHM_SYSTEM_NAME				"NRMKSystemData"
#define NRMK_SHM_NAME						NRMK_SHM_SYSTEM_NAME
#define NRMK_SHM_SYSTEM_LEN 				0x8000		//32KB
#define NRMK_SHM_SYSTEM_START			 	0x0000
#define NRMK_SHM_SYSTEM_END		 			0x7FFF

/* System Status Data */
#define NRMK_SHM_SYSTEM_ADDR_STRUCT_DATA					0x0000
#define NRMK_SHM_SYSTEM_ADDR_RUNNING_TIME					0x0000
#define NRMK_SHM_SYSTEM_ADDR_RT_CYCLE_TIME					0x0008
#define NRMK_SHM_SYSTEM_ADDR_RT_CYCLE_JITTER				0x0010
#define NRMK_SHM_SYSTEM_ADDR_TASK_EXEC_PERIOD				0x0018
#define NRMK_SHM_SYSTEM_ADDR_TASK_EXEC_PERIOD_MAX			0x0020
#define NRMK_SHM_SYSTEM_ADDR_OVERRUN_COUNT					0x0028

/* System Info Shared Data*/
#define NRMK_SHM_SYSTEM_INFO_ADDR_STRUCT_DATA				0x0200
#define NRMK_SHM_SYSTEM_INFO_ADDR_RT_TIMER_RATE				0x0200

/* Task Info Shared Data*/
#define NRMK_SHM_SYSTEM_TASK_INFO_STRUCTS_START_ADDR		0x4000	//~0x7FFF (256*32)
#define NRMK_SHM_SYSTEM_TASK_INFO_STRUCT_SIZE				256
#define NRMK_SHM_SYSTEM_TASK_INFO_STRUCT_MAX_NUM			64

#endif /* NRMKFRAMEWORK_SHAREDMEMORYADDRESS_H_ */
