/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) indy7_v2_fkrot_ee_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* fk_rot:(q[7])->(Rot_tcp_fixed[3x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][1] : 0;
  a3=cos(a2);
  a4=(a1*a3);
  a5=arg[0]? arg[0][2] : 0;
  a6=cos(a5);
  a7=(a4*a6);
  a0=sin(a0);
  a5=sin(a5);
  a8=(a0*a5);
  a7=(a7-a8);
  a8=arg[0]? arg[0][3] : 0;
  a9=cos(a8);
  a10=(a7*a9);
  a2=sin(a2);
  a11=(a1*a2);
  a8=sin(a8);
  a12=(a11*a8);
  a10=(a10-a12);
  a12=arg[0]? arg[0][4] : 0;
  a13=cos(a12);
  a14=(a10*a13);
  a4=(a4*a5);
  a15=(a0*a6);
  a4=(a4+a15);
  a12=sin(a12);
  a15=(a4*a12);
  a14=(a14-a15);
  a15=arg[0]? arg[0][5] : 0;
  a16=cos(a15);
  a17=(a14*a16);
  a7=(a7*a8);
  a11=(a11*a9);
  a7=(a7+a11);
  a15=sin(a15);
  a11=(a7*a15);
  a17=(a17-a11);
  a11=arg[0]? arg[0][6] : 0;
  a18=cos(a11);
  a19=(a17*a18);
  a10=(a10*a12);
  a4=(a4*a13);
  a10=(a10+a4);
  a11=sin(a11);
  a4=(a10*a11);
  a19=(a19-a4);
  if (res[0]!=0) res[0][0]=a19;
  a19=(a0*a3);
  a4=(a19*a6);
  a20=(a1*a5);
  a4=(a4+a20);
  a20=(a4*a9);
  a0=(a0*a2);
  a21=(a0*a8);
  a20=(a20-a21);
  a21=(a20*a13);
  a1=(a1*a6);
  a19=(a19*a5);
  a1=(a1-a19);
  a19=(a1*a12);
  a21=(a21+a19);
  a19=(a21*a16);
  a4=(a4*a8);
  a0=(a0*a9);
  a4=(a4+a0);
  a0=(a4*a15);
  a19=(a19-a0);
  a0=(a19*a18);
  a1=(a1*a13);
  a20=(a20*a12);
  a1=(a1-a20);
  a20=(a1*a11);
  a0=(a0+a20);
  if (res[0]!=0) res[0][1]=a0;
  a5=(a2*a5);
  a0=(a5*a12);
  a2=(a2*a6);
  a6=(a2*a9);
  a20=(a3*a8);
  a6=(a6+a20);
  a20=(a6*a13);
  a0=(a0-a20);
  a20=(a0*a16);
  a3=(a3*a9);
  a2=(a2*a8);
  a3=(a3-a2);
  a2=(a3*a15);
  a20=(a20-a2);
  a2=(a20*a18);
  a6=(a6*a12);
  a5=(a5*a13);
  a6=(a6+a5);
  a5=(a6*a11);
  a2=(a2+a5);
  if (res[0]!=0) res[0][2]=a2;
  a17=(a17*a11);
  a10=(a10*a18);
  a17=(a17+a10);
  a17=(-a17);
  if (res[0]!=0) res[0][3]=a17;
  a1=(a1*a18);
  a19=(a19*a11);
  a1=(a1-a19);
  if (res[0]!=0) res[0][4]=a1;
  a6=(a6*a18);
  a20=(a20*a11);
  a6=(a6-a20);
  if (res[0]!=0) res[0][5]=a6;
  a14=(a14*a15);
  a7=(a7*a16);
  a14=(a14+a7);
  if (res[0]!=0) res[0][6]=a14;
  a21=(a21*a15);
  a4=(a4*a16);
  a21=(a21+a4);
  if (res[0]!=0) res[0][7]=a21;
  a0=(a0*a15);
  a3=(a3*a16);
  a0=(a0+a3);
  if (res[0]!=0) res[0][8]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fk_rot(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fk_rot_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fk_rot_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fk_rot_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fk_rot_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fk_rot_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fk_rot_incref(void) {
}

CASADI_SYMBOL_EXPORT void fk_rot_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fk_rot_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int fk_rot_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fk_rot_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fk_rot_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fk_rot_name_out(casadi_int i) {
  switch (i) {
    case 0: return "Rot_tcp_fixed";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fk_rot_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fk_rot_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fk_rot_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fk_rot_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
