/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) indy7_v2_fk_ee_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};

/* fk_T:(q[7])->(T_tcp_fixed[4x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][0] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][1] : 0;
  a3=cos(a2);
  a4=(a1*a3);
  a5=arg[0]? arg[0][2] : 0;
  a6=cos(a5);
  a7=(a4*a6);
  a0=sin(a0);
  a5=sin(a5);
  a8=(a0*a5);
  a7=(a7-a8);
  a8=arg[0]? arg[0][3] : 0;
  a9=cos(a8);
  a10=(a7*a9);
  a2=sin(a2);
  a11=(a1*a2);
  a8=sin(a8);
  a12=(a11*a8);
  a10=(a10-a12);
  a12=arg[0]? arg[0][4] : 0;
  a13=cos(a12);
  a14=(a10*a13);
  a4=(a4*a5);
  a15=(a0*a6);
  a4=(a4+a15);
  a12=sin(a12);
  a15=(a4*a12);
  a14=(a14-a15);
  a15=arg[0]? arg[0][5] : 0;
  a16=cos(a15);
  a17=(a14*a16);
  a7=(a7*a8);
  a18=(a11*a9);
  a7=(a7+a18);
  a15=sin(a15);
  a18=(a7*a15);
  a17=(a17-a18);
  a18=arg[0]? arg[0][6] : 0;
  a19=cos(a18);
  a20=(a17*a19);
  a10=(a10*a12);
  a21=(a4*a13);
  a10=(a10+a21);
  a18=sin(a18);
  a21=(a10*a18);
  a20=(a20-a21);
  if (res[0]!=0) res[0][0]=a20;
  a20=(a0*a3);
  a21=(a20*a6);
  a22=(a1*a5);
  a21=(a21+a22);
  a22=(a21*a9);
  a23=(a0*a2);
  a24=(a23*a8);
  a22=(a22-a24);
  a24=(a22*a13);
  a25=(a1*a6);
  a20=(a20*a5);
  a25=(a25-a20);
  a20=(a25*a12);
  a24=(a24+a20);
  a20=(a24*a16);
  a21=(a21*a8);
  a26=(a23*a9);
  a21=(a21+a26);
  a26=(a21*a15);
  a20=(a20-a26);
  a26=(a20*a19);
  a27=(a25*a13);
  a22=(a22*a12);
  a27=(a27-a22);
  a22=(a27*a18);
  a26=(a26+a22);
  if (res[0]!=0) res[0][1]=a26;
  a5=(a2*a5);
  a26=(a5*a12);
  a2=(a2*a6);
  a6=(a2*a9);
  a22=(a3*a8);
  a6=(a6+a22);
  a22=(a6*a13);
  a26=(a26-a22);
  a22=(a26*a16);
  a9=(a3*a9);
  a2=(a2*a8);
  a9=(a9-a2);
  a2=(a9*a15);
  a22=(a22-a2);
  a2=(a22*a19);
  a6=(a6*a12);
  a13=(a5*a13);
  a6=(a6+a13);
  a13=(a6*a18);
  a2=(a2+a13);
  if (res[0]!=0) res[0][2]=a2;
  a2=0.;
  if (res[0]!=0) res[0][3]=a2;
  a17=(a17*a18);
  a13=(a10*a19);
  a17=(a17+a13);
  a17=(-a17);
  if (res[0]!=0) res[0][4]=a17;
  a17=(a27*a19);
  a20=(a20*a18);
  a17=(a17-a20);
  if (res[0]!=0) res[0][5]=a17;
  a19=(a6*a19);
  a22=(a22*a18);
  a19=(a19-a22);
  if (res[0]!=0) res[0][6]=a19;
  if (res[0]!=0) res[0][7]=a2;
  a14=(a14*a15);
  a19=(a7*a16);
  a14=(a14+a19);
  if (res[0]!=0) res[0][8]=a14;
  a24=(a24*a15);
  a19=(a21*a16);
  a24=(a24+a19);
  if (res[0]!=0) res[0][9]=a24;
  a26=(a26*a15);
  a16=(a9*a16);
  a26=(a26+a16);
  if (res[0]!=0) res[0][10]=a26;
  if (res[0]!=0) res[0][11]=a2;
  a2=2.9299999999999998e-01;
  a16=(a2*a11);
  a15=-1.1100000000000000e-01;
  a19=(a15*a0);
  a16=(a16-a19);
  a19=-1.3600000000000001e-01;
  a0=(a19*a0);
  a16=(a16-a0);
  a0=3.5749999999999998e-01;
  a11=(a0*a11);
  a22=1.2950000000000000e-01;
  a18=(a22*a4);
  a11=(a11-a18);
  a16=(a16+a11);
  a11=2.0899999999999999e-01;
  a18=(a11*a7);
  a17=1.0650000000000000e-01;
  a4=(a17*a4);
  a18=(a18-a4);
  a16=(a16+a18);
  a18=3.6249999999999999e-01;
  a7=(a18*a7);
  a4=-1.2900000000000000e-01;
  a20=(a4*a10);
  a7=(a7-a20);
  a16=(a16+a7);
  a7=7.4550000000000005e-02;
  a20=(a7*a14);
  a13=-7.9500000000000001e-02;
  a10=(a13*a10);
  a20=(a20-a10);
  a16=(a16+a20);
  a20=8.4099999999999994e-02;
  a14=(a20*a14);
  a16=(a16+a14);
  if (res[0]!=0) res[0][12]=a16;
  a19=(a19*a1);
  a15=(a15*a1);
  a1=(a2*a23);
  a15=(a15+a1);
  a19=(a19+a15);
  a15=(a22*a25);
  a23=(a0*a23);
  a15=(a15+a23);
  a19=(a19+a15);
  a25=(a17*a25);
  a15=(a11*a21);
  a25=(a25+a15);
  a19=(a19+a25);
  a25=(a4*a27);
  a21=(a18*a21);
  a25=(a25+a21);
  a19=(a19+a25);
  a27=(a13*a27);
  a25=(a7*a24);
  a27=(a27+a25);
  a19=(a19+a27);
  a24=(a20*a24);
  a19=(a19+a24);
  if (res[0]!=0) res[0][13]=a19;
  a19=3.5000000000000003e-01;
  a2=(a2*a3);
  a19=(a19+a2);
  a22=(a22*a5);
  a0=(a0*a3);
  a22=(a22+a0);
  a19=(a19+a22);
  a17=(a17*a5);
  a11=(a11*a9);
  a17=(a17+a11);
  a19=(a19+a17);
  a4=(a4*a6);
  a18=(a18*a9);
  a4=(a4+a18);
  a19=(a19+a4);
  a13=(a13*a6);
  a7=(a7*a26);
  a13=(a13+a7);
  a19=(a19+a13);
  a20=(a20*a26);
  a19=(a19+a20);
  if (res[0]!=0) res[0][14]=a19;
  a19=1.;
  if (res[0]!=0) res[0][15]=a19;
  return 0;
}

CASADI_SYMBOL_EXPORT int fk_T(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fk_T_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fk_T_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fk_T_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fk_T_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fk_T_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fk_T_incref(void) {
}

CASADI_SYMBOL_EXPORT void fk_T_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fk_T_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int fk_T_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fk_T_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fk_T_name_in(casadi_int i) {
  switch (i) {
    case 0: return "q";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fk_T_name_out(casadi_int i) {
  switch (i) {
    case 0: return "T_tcp_fixed";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fk_T_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fk_T_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fk_T_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fk_T_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
