/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) indy7_v2_M_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[59] = {7, 7, 0, 7, 14, 21, 28, 35, 42, 49, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};

/* M:(i0[7])->(o0[7x7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a8, a9;
  a0=1.0765690999999999e-01;
  a1=3.7755720000000000e-02;
  a2=3.1009030000000000e-02;
  a3=1.6158920000000000e-02;
  a4=1.9273709999999999e-02;
  a5=8.2640300004152411e-03;
  a6=7.8398111203041798e-01;
  a7=-1.4038000000000001e-04;
  a8=3.1149969061889857e-04;
  a9=arg[0]? arg[0][6] : 0;
  a10=cos(a9);
  a11=(a8*a10);
  a12=-5.6409943973714512e-04;
  a9=sin(a9);
  a13=(a12*a9);
  a11=(a11-a13);
  a13=(a7-a11);
  a14=casadi_sq(a13);
  a15=-7.9500000000000001e-02;
  a8=(a8*a9);
  a12=(a12*a10);
  a8=(a8+a12);
  a8=(a15+a8);
  a7=(a7-a8);
  a12=casadi_sq(a7);
  a14=(a14+a12);
  a14=(a6*a14);
  a5=(a5+a14);
  a14=arg[0]? arg[0][5] : 0;
  a12=cos(a14);
  a16=2.;
  a17=-5.5000000000000003e-07;
  a18=1.6600296798151220e-06;
  a19=(a18*a10);
  a20=-3.9800537476202579e-06;
  a21=(a20*a9);
  a19=(a19-a21);
  a21=8.3001483990756100e-07;
  a22=(a21*a10);
  a23=-1.9900268738101290e-06;
  a24=(a23*a9);
  a22=(a22-a24);
  a19=(a19-a22);
  a17=(a17+a19);
  a19=-9.0660627316139802e-02;
  a22=(a6*a13);
  a22=(a19*a22);
  a17=(a17-a22);
  a22=(a16*a17);
  a22=(a12*a22);
  a14=sin(a14);
  a24=9.4730900000000000e-03;
  a25=-9.8983546124243780e-04;
  a26=-4.9063773051063065e-04;
  a26=(a26*a9);
  a27=1.8000017571697548e-07;
  a28=(a27*a10);
  a26=(a26+a28);
  a28=(a26*a9);
  a27=(a27*a9);
  a29=-4.9919773073180715e-04;
  a29=(a29*a10);
  a27=(a27+a29);
  a29=(a27*a10);
  a28=(a28+a29);
  a25=(a25-a28);
  a29=2.2328300004152411e-03;
  a25=(a25+a29);
  a24=(a24+a25);
  a25=casadi_sq(a7);
  a30=8.2193493453559946e-03;
  a25=(a25+a30);
  a25=(a6*a25);
  a24=(a24+a25);
  a24=(a24-a5);
  a25=(a14*a24);
  a22=(a22-a25);
  a25=(a22*a14);
  a31=(a5-a25);
  a4=(a4+a31);
  a31=2.3941815016869974e+00;
  a32=1.5551000000000001e-04;
  a33=-1.0930664587138675e-04;
  a34=2.2135171768494971e-01;
  a11=(a34*a11);
  a11=(a33+a11);
  a35=(a12*a11);
  a36=4.0417105582822618e-02;
  a37=(a36*a14);
  a35=(a35+a37);
  a32=(a32-a35);
  a37=casadi_sq(a32);
  a38=-4.6691280000000002e-02;
  a39=-1.2900000000000000e-01;
  a34=(a34*a8);
  a33=(a33+a34);
  a34=(a39+a33);
  a38=(a38-a34);
  a8=casadi_sq(a38);
  a37=(a37+a8);
  a37=(a31*a37);
  a4=(a4+a37);
  a3=(a3+a4);
  a37=3.3343442709439617e+00;
  a8=-4.8300000000000003e-06;
  a40=arg[0]? arg[0][4] : 0;
  a41=cos(a40);
  a42=8.1852890241958739e-05;
  a43=4.7364870270748677e-01;
  a35=(a43*a35);
  a42=(a42+a35);
  a35=(a41*a42);
  a40=sin(a40);
  a44=-2.4576015800247982e-02;
  a34=(a43*a34);
  a44=(a44+a34);
  a34=(a40*a44);
  a35=(a35-a34);
  a8=(a8-a35);
  a34=casadi_sq(a8);
  a45=8.9583410000000002e-02;
  a46=1.0650000000000000e-01;
  a47=(a40*a42);
  a48=(a41*a44);
  a47=(a47+a48);
  a47=(a46+a47);
  a45=(a45-a47);
  a48=casadi_sq(a45);
  a34=(a34+a48);
  a34=(a37*a34);
  a3=(a3+a34);
  a34=arg[0]? arg[0][3] : 0;
  a48=cos(a34);
  a49=5.0999999999999999e-07;
  a50=8.1489999999999994e-05;
  a22=(a22*a12);
  a22=(a22-a17);
  a50=(a50+a22);
  a22=(a31*a32);
  a17=2.2088569999999999e-01;
  a51=3.6249999999999999e-01;
  a52=(a36*a12);
  a53=(a14*a11);
  a52=(a52-a53);
  a52=(a51+a52);
  a17=(a17-a52);
  a22=(a22*a17);
  a50=(a50-a22);
  a22=(a16*a50);
  a53=(a22*a41);
  a54=-2.3741040000000001e-02;
  a55=-3.8601000000000000e-04;
  a18=(a18*a9);
  a20=(a20*a10);
  a18=(a18+a20);
  a23=(a23*a10);
  a21=(a21*a9);
  a23=(a23+a21);
  a18=(a18-a23);
  a55=(a55+a18);
  a18=(a6*a7);
  a19=(a19*a18);
  a55=(a55-a19);
  a19=(a55+a55);
  a19=(a12*a19);
  a18=3.6799999999999999e-06;
  a26=(a26*a10);
  a27=(a27*a9);
  a26=(a26-a27);
  a18=(a18+a26);
  a26=(a6*a13);
  a26=(a26*a7);
  a18=(a18-a26);
  a26=(a14*a18);
  a19=(a19-a26);
  a26=(a12*a55);
  a19=(a19-a26);
  a54=(a54+a19);
  a19=(a31*a38);
  a19=(a19*a17);
  a54=(a54-a19);
  a19=(a54+a54);
  a26=(a19*a40);
  a53=(a53-a26);
  a26=(a41*a50);
  a7=(a40*a54);
  a26=(a26-a7);
  a53=(a53-a26);
  a49=(a49+a53);
  a53=(a37*a8);
  a26=6.6920259999999995e-02;
  a7=2.0899999999999999e-01;
  a27=1.1626347474836490e-01;
  a43=(a43*a52);
  a27=(a27+a43);
  a43=(a7+a27);
  a26=(a26-a43);
  a53=(a53*a26);
  a49=(a49-a53);
  a53=(a16*a49);
  a53=(a48*a53);
  a34=sin(a34);
  a52=3.9503419999999997e-02;
  a23=1.0945505000000000e-01;
  a24=(a24+a25);
  a24=(a24+a5);
  a23=(a23+a24);
  a24=casadi_sq(a38);
  a5=casadi_sq(a17);
  a24=(a24+a5);
  a24=(a31*a24);
  a23=(a23+a24);
  a23=(a23-a4);
  a24=1.0032484000000000e-01;
  a5=9.0189999999999992e-03;
  a28=(a28+a29);
  a5=(a5+a28);
  a13=casadi_sq(a13);
  a13=(a13+a30);
  a6=(a6*a13);
  a5=(a5+a6);
  a24=(a24+a5);
  a6=casadi_sq(a32);
  a17=casadi_sq(a17);
  a6=(a6+a17);
  a6=(a31*a6);
  a24=(a24+a6);
  a24=(a24-a4);
  a6=(a23+a24);
  a23=(a40*a23);
  a17=-8.3250000000000004e-05;
  a13=(a18*a12);
  a30=(a14*a55);
  a13=(a13+a30);
  a17=(a17+a13);
  a31=(a31*a32);
  a31=(a31*a38);
  a17=(a17-a31);
  a31=(a41*a17);
  a23=(a23+a31);
  a31=(a23*a40);
  a17=(a40*a17);
  a24=(a41*a24);
  a17=(a17+a24);
  a24=(a17*a41);
  a31=(a31+a24);
  a6=(a6-a31);
  a6=(a6+a4);
  a52=(a52+a6);
  a6=casadi_sq(a45);
  a24=casadi_sq(a26);
  a6=(a6+a24);
  a6=(a37*a6);
  a52=(a52+a6);
  a52=(a52-a3);
  a6=(a34*a52);
  a53=(a53-a6);
  a6=(a53*a34);
  a24=(a3-a6);
  a2=(a2+a24);
  a24=5.3697516921302064e+00;
  a38=1.7700000000000000e-06;
  a32=-1.6769980140408037e-06;
  a13=6.5279544222757691e-01;
  a35=(a13*a35);
  a32=(a32+a35);
  a35=(a48*a32);
  a30=2.3235019279315573e-02;
  a43=(a13*a43);
  a30=(a30+a43);
  a43=(a34*a30);
  a35=(a35+a43);
  a38=(a38-a35);
  a43=casadi_sq(a38);
  a28=1.8148879999999999e-02;
  a29=1.2950000000000000e-01;
  a25=3.1103768252795667e-02;
  a13=(a13*a47);
  a25=(a25+a13);
  a13=(a29+a25);
  a28=(a28-a13);
  a47=casadi_sq(a28);
  a43=(a43+a47);
  a43=(a24*a43);
  a2=(a2+a43);
  a1=(a1+a2);
  a43=6.4660272747639391e+00;
  a47=arg[0]? arg[0][2] : 0;
  a21=cos(a47);
  a20=6.4606998076200725e-07;
  a56=6.3498871143389413e-01;
  a35=(a56*a35);
  a20=(a20+a35);
  a35=(a21*a20);
  a47=sin(a47);
  a57=6.6245460748316255e-03;
  a13=(a56*a13);
  a57=(a57+a13);
  a13=(a47*a57);
  a35=(a35-a13);
  a13=casadi_sq(a35);
  a58=-9.5824909999999999e-02;
  a59=-1.1100000000000000e-01;
  a60=(a47*a20);
  a61=(a21*a57);
  a60=(a60+a61);
  a60=(a59+a60);
  a58=(a58-a60);
  a61=casadi_sq(a58);
  a13=(a13+a61);
  a13=(a43*a13);
  a1=(a1+a13);
  a13=arg[0]? arg[0][1] : 0;
  a61=cos(a13);
  a62=4.0999999999999999e-07;
  a63=1.7300000000000000e-06;
  a53=(a53*a48);
  a53=(a53-a49);
  a63=(a63+a53);
  a53=(a24*a38);
  a49=2.1567452000000001e-01;
  a64=3.5749999999999998e-01;
  a65=(a48*a30);
  a66=(a34*a32);
  a65=(a65-a66);
  a65=(a64+a65);
  a49=(a49-a65);
  a53=(a53*a49);
  a63=(a63-a53);
  a53=(a16*a63);
  a66=(a53*a21);
  a67=1.9436650000000000e-02;
  a68=6.3932700000000004e-03;
  a22=(a22*a40);
  a19=(a19*a41);
  a22=(a22+a19);
  a19=(a41*a54);
  a69=(a40*a50);
  a19=(a19+a69);
  a22=(a22-a19);
  a68=(a68+a22);
  a22=(a37*a45);
  a22=(a22*a26);
  a68=(a68-a22);
  a22=(a68+a68);
  a22=(a48*a22);
  a19=6.0999999999999998e-07;
  a23=(a23*a41);
  a17=(a17*a40);
  a23=(a23-a17);
  a19=(a19+a23);
  a23=(a37*a8);
  a23=(a23*a45);
  a19=(a19-a23);
  a23=(a34*a19);
  a22=(a22-a23);
  a23=(a48*a68);
  a22=(a22-a23);
  a67=(a67+a22);
  a22=(a24*a28);
  a22=(a22*a49);
  a67=(a67-a22);
  a22=(a67+a67);
  a23=(a22*a47);
  a66=(a66-a23);
  a23=(a21*a63);
  a45=(a47*a67);
  a23=(a23-a45);
  a66=(a66-a23);
  a62=(a62+a66);
  a66=(a43*a35);
  a23=8.8479459999999996e-02;
  a45=2.9299999999999998e-01;
  a17=7.8723634456076358e-02;
  a56=(a56*a65);
  a17=(a17+a56);
  a56=(a45+a17);
  a23=(a23-a56);
  a66=(a66*a23);
  a62=(a62+a66);
  a16=(a16*a62);
  a16=(a61*a16);
  a13=sin(a13);
  a62=1.0217692000000000e-01;
  a66=1.4750526999999999e-01;
  a52=(a52+a6);
  a52=(a52+a3);
  a66=(a66+a52);
  a52=casadi_sq(a28);
  a3=casadi_sq(a49);
  a52=(a52+a3);
  a52=(a24*a52);
  a66=(a66+a52);
  a66=(a66-a2);
  a52=1.4140191999999999e-01;
  a3=3.6442179999999998e-02;
  a31=(a31+a4);
  a3=(a3+a31);
  a8=casadi_sq(a8);
  a26=casadi_sq(a26);
  a8=(a8+a26);
  a37=(a37*a8);
  a3=(a3+a37);
  a52=(a52+a3);
  a37=casadi_sq(a38);
  a49=casadi_sq(a49);
  a37=(a37+a49);
  a37=(a24*a37);
  a52=(a52+a37);
  a52=(a52-a2);
  a37=(a66+a52);
  a66=(a47*a66);
  a49=6.7000000000000004e-07;
  a8=(a19*a48);
  a26=(a34*a68);
  a8=(a8+a26);
  a49=(a49+a8);
  a24=(a24*a38);
  a24=(a24*a28);
  a49=(a49-a24);
  a24=(a21*a49);
  a66=(a66+a24);
  a24=(a66*a47);
  a49=(a47*a49);
  a52=(a21*a52);
  a49=(a49+a52);
  a52=(a49*a21);
  a24=(a24+a52);
  a37=(a37-a24);
  a37=(a37+a2);
  a62=(a62+a37);
  a37=casadi_sq(a58);
  a52=casadi_sq(a23);
  a37=(a37+a52);
  a37=(a43*a37);
  a62=(a62+a37);
  a62=(a62-a1);
  a62=(a13*a62);
  a16=(a16-a62);
  a16=(a16*a13);
  a1=(a1-a16);
  a0=(a0+a1);
  a1=1.3422487395654999e+01;
  a16=8.5569999999999996e-05;
  a62=7.2090270377520749e-01;
  a37=(a62*a35);
  a52=(a61*a37);
  a28=2.4694378057429675e-02;
  a56=(a62*a56);
  a28=(a28+a56);
  a56=(a13*a28);
  a52=(a52+a56);
  a16=(a16-a52);
  a16=casadi_sq(a16);
  a56=-4.3281540000000000e-02;
  a38=-1.3600000000000001e-01;
  a8=-2.6744473291984077e-02;
  a62=(a62*a60);
  a8=(a8+a62);
  a62=(a38+a8);
  a56=(a56-a62);
  a56=casadi_sq(a56);
  a16=(a16+a56);
  a1=(a1*a16);
  a0=(a0+a1);
  a1=5.5186407160000002e+01;
  a16=3.5739567137682463e-05;
  a56=5.8233531450645726e-01;
  a52=(a56*a52);
  a16=(a16+a52);
  a16=casadi_sq(a16);
  a52=-1.8077170791776193e-02;
  a56=(a56*a62);
  a52=(a52+a56);
  a52=casadi_sq(a52);
  a16=(a16+a52);
  a1=(a1*a16);
  a0=(a0+a1);
  if (res[0]!=0) res[0][0]=a0;
  a0=-1.3421940000000000e-02;
  a53=(a53*a47);
  a22=(a22*a21);
  a53=(a53+a22);
  a22=(a21*a67);
  a1=(a47*a63);
  a22=(a22+a1);
  a53=(a53-a22);
  a0=(a0+a53);
  a53=(a43*a58);
  a53=(a53*a23);
  a0=(a0-a53);
  a53=3.2136993770000004e+01;
  a22=(a53*a8);
  a22=(a22*a28);
  a0=(a0-a22);
  a0=(a61*a0);
  a22=-3.8000000000000001e-07;
  a66=(a66*a21);
  a49=(a49*a47);
  a66=(a66-a49);
  a22=(a22+a66);
  a66=(a43*a35);
  a66=(a66*a58);
  a22=(a22+a66);
  a66=(a53*a37);
  a66=(a66*a8);
  a22=(a22-a66);
  a22=(a13*a22);
  a0=(a0-a22);
  a22=(a53*a28);
  a22=(a61*a22);
  a66=-3.2136993770000004e+01;
  a66=(a66*a37);
  a66=(a13*a66);
  a22=(a22+a66);
  a22=(a38*a22);
  a0=(a0-a22);
  if (res[0]!=0) res[0][1]=a0;
  a22=2.3167645700000001e+01;
  a66=casadi_sq(a20);
  a8=casadi_sq(a57);
  a66=(a66+a8);
  a66=(a22*a66);
  a66=(a2+a66);
  a8=-2.3167645700000001e+01;
  a8=(a8*a57);
  a58=(a21*a8);
  a49=(a22*a20);
  a1=(a47*a49);
  a58=(a58-a1);
  a1=(a59*a58);
  a1=(a66-a1);
  a1=(a61*a1);
  a20=(a22*a20);
  a20=(a20*a17);
  a63=(a63-a20);
  a20=(a21*a63);
  a22=(a22*a57);
  a22=(a22*a17);
  a67=(a67-a22);
  a22=(a47*a67);
  a20=(a20-a22);
  a8=(a47*a8);
  a49=(a21*a49);
  a8=(a8+a49);
  a8=(a45*a8);
  a20=(a20-a8);
  a20=(a13*a20);
  a1=(a1-a20);
  a20=(a61*a58);
  a20=(a38*a20);
  a1=(a1-a20);
  if (res[0]!=0) res[0][2]=a1;
  a20=1.4711193489999999e+01;
  a8=(a20*a25);
  a8=(a8*a30);
  a68=(a68-a8);
  a8=(a48*a68);
  a49=(a20*a32);
  a49=(a49*a25);
  a19=(a19-a49);
  a49=(a34*a19);
  a8=(a8-a49);
  a49=(a20*a30);
  a25=(a48*a49);
  a22=-1.4711193489999999e+01;
  a22=(a22*a32);
  a17=(a34*a22);
  a25=(a25+a17);
  a17=(a29*a25);
  a8=(a8-a17);
  a17=(a21*a25);
  a57=(a59*a17);
  a57=(a8-a57);
  a57=(a61*a57);
  a19=(a48*a19);
  a68=(a34*a68);
  a19=(a19+a68);
  a22=(a48*a22);
  a49=(a34*a49);
  a22=(a22-a49);
  a49=(a29*a22);
  a19=(a19+a49);
  a49=(a21*a19);
  a32=casadi_sq(a32);
  a30=casadi_sq(a30);
  a32=(a32+a30);
  a20=(a20*a32);
  a3=(a3+a20);
  a20=(a64*a25);
  a20=(a3+a20);
  a32=(a47*a20);
  a49=(a49-a32);
  a32=(a59*a22);
  a25=(a47*a25);
  a25=(a45*a25);
  a32=(a32-a25);
  a49=(a49+a32);
  a49=(a13*a49);
  a57=(a57-a49);
  a49=(a61*a17);
  a22=(a13*a22);
  a49=(a49+a22);
  a49=(a38*a49);
  a57=(a57-a49);
  if (res[0]!=0) res[0][3]=a57;
  a49=9.6034000600000002e+00;
  a22=casadi_sq(a42);
  a32=casadi_sq(a44);
  a22=(a22+a32);
  a22=(a49*a22);
  a4=(a4+a22);
  a22=-9.6034000600000002e+00;
  a22=(a22*a44);
  a32=(a41*a22);
  a25=(a49*a42);
  a30=(a40*a25);
  a32=(a32-a30);
  a30=(a46*a32);
  a30=(a4-a30);
  a68=(a48*a30);
  a42=(a49*a42);
  a42=(a42*a27);
  a50=(a50-a42);
  a42=(a41*a50);
  a49=(a49*a44);
  a49=(a49*a27);
  a54=(a54-a49);
  a49=(a40*a54);
  a42=(a42-a49);
  a22=(a40*a22);
  a25=(a41*a25);
  a22=(a22+a25);
  a25=(a7*a22);
  a42=(a42-a25);
  a25=(a34*a42);
  a68=(a68-a25);
  a25=(a48*a32);
  a49=(a29*a25);
  a68=(a68-a49);
  a49=(a21*a25);
  a27=(a47*a22);
  a49=(a49-a27);
  a27=(a59*a49);
  a27=(a68-a27);
  a27=(a61*a27);
  a42=(a48*a42);
  a30=(a34*a30);
  a42=(a42+a30);
  a30=(a34*a32);
  a44=(a29*a30);
  a16=(a64*a22);
  a44=(a44+a16);
  a42=(a42-a44);
  a44=(a21*a42);
  a50=(a40*a50);
  a54=(a41*a54);
  a50=(a50+a54);
  a32=(a7*a32);
  a50=(a50+a32);
  a32=(a64*a25);
  a32=(a50+a32);
  a54=(a47*a32);
  a44=(a44-a54);
  a54=(a59*a30);
  a25=(a47*a25);
  a22=(a21*a22);
  a25=(a25+a22);
  a25=(a45*a25);
  a54=(a54+a25);
  a44=(a44-a54);
  a44=(a13*a44);
  a27=(a27-a44);
  a44=(a61*a49);
  a30=(a13*a30);
  a44=(a44-a30);
  a44=(a38*a44);
  a27=(a27-a44);
  if (res[0]!=0) res[0][4]=a27;
  a44=4.5486379800000005e+00;
  a30=(a44*a33);
  a36=(a36*a30);
  a55=(a55-a36);
  a36=(a12*a55);
  a30=(a44*a11);
  a30=(a30*a33);
  a18=(a18-a30);
  a30=(a14*a18);
  a36=(a36-a30);
  a30=1.8384278149569702e-01;
  a33=(a30*a12);
  a54=-4.5486379800000005e+00;
  a54=(a54*a11);
  a25=(a14*a54);
  a33=(a33+a25);
  a25=(a39*a33);
  a36=(a36-a25);
  a25=(a41*a33);
  a22=(a46*a25);
  a22=(a36-a22);
  a16=(a48*a22);
  a18=(a12*a18);
  a55=(a14*a55);
  a18=(a18+a55);
  a54=(a12*a54);
  a30=(a30*a14);
  a54=(a54-a30);
  a30=(a39*a54);
  a18=(a18+a30);
  a30=(a41*a18);
  a11=casadi_sq(a11);
  a55=1.6335424236930312e-03;
  a11=(a11+a55);
  a44=(a44*a11);
  a5=(a5+a44);
  a44=(a51*a33);
  a44=(a5+a44);
  a11=(a40*a44);
  a30=(a30-a11);
  a11=(a46*a54);
  a33=(a40*a33);
  a55=(a7*a33);
  a11=(a11-a55);
  a30=(a30+a11);
  a11=(a34*a30);
  a16=(a16-a11);
  a11=(a48*a25);
  a55=(a34*a54);
  a11=(a11+a55);
  a55=(a29*a11);
  a16=(a16-a55);
  a55=(a21*a11);
  a52=(a47*a33);
  a55=(a55-a52);
  a52=(a59*a55);
  a52=(a16-a52);
  a52=(a61*a52);
  a30=(a48*a30);
  a22=(a34*a22);
  a30=(a30+a22);
  a54=(a48*a54);
  a22=(a34*a25);
  a54=(a54-a22);
  a22=(a29*a54);
  a56=(a64*a33);
  a22=(a22-a56);
  a30=(a30+a22);
  a22=(a21*a30);
  a18=(a40*a18);
  a44=(a41*a44);
  a18=(a18+a44);
  a25=(a7*a25);
  a18=(a18+a25);
  a25=(a64*a11);
  a25=(a18+a25);
  a44=(a47*a25);
  a22=(a22-a44);
  a44=(a59*a54);
  a11=(a47*a11);
  a33=(a21*a33);
  a11=(a11+a33);
  a11=(a45*a11);
  a44=(a44-a11);
  a22=(a22+a44);
  a22=(a13*a22);
  a52=(a52-a22);
  a22=(a61*a55);
  a54=(a13*a54);
  a22=(a22+a54);
  a22=(a38*a22);
  a52=(a52-a22);
  if (res[0]!=0) res[0][5]=a52;
  a22=2.2332480845601885e-03;
  a54=5.6796286090300013e-04;
  a44=(a54*a10);
  a11=3.1363309904500002e-04;
  a33=(a11*a9);
  a44=(a44-a33);
  a15=(a15*a44);
  a15=(a22-a15);
  a33=(a12*a15);
  a56=-1.0605000064560893e-05;
  a62=(a56*a10);
  a60=1.8717812315951206e-05;
  a26=(a60*a9);
  a62=(a62-a26);
  a26=7.4550000000000005e-02;
  a54=(a54*a9);
  a11=(a11*a10);
  a54=(a54+a11);
  a11=(a26*a54);
  a62=(a62-a11);
  a11=(a14*a62);
  a33=(a33-a11);
  a11=(a12*a44);
  a31=(a39*a11);
  a33=(a33-a31);
  a31=(a41*a11);
  a6=(a40*a54);
  a31=(a31-a6);
  a6=(a46*a31);
  a6=(a33-a6);
  a65=(a48*a6);
  a12=(a12*a62);
  a15=(a14*a15);
  a12=(a12+a15);
  a14=(a14*a44);
  a39=(a39*a14);
  a15=(a51*a54);
  a39=(a39+a15);
  a12=(a12-a39);
  a39=(a41*a12);
  a56=(a56*a9);
  a60=(a60*a10);
  a56=(a56+a60);
  a26=(a26*a44);
  a56=(a56+a26);
  a51=(a51*a11);
  a51=(a56+a51);
  a26=(a40*a51);
  a39=(a39-a26);
  a46=(a46*a14);
  a11=(a40*a11);
  a54=(a41*a54);
  a11=(a11+a54);
  a54=(a7*a11);
  a46=(a46+a54);
  a39=(a39-a46);
  a46=(a34*a39);
  a65=(a65-a46);
  a46=(a48*a31);
  a54=(a34*a14);
  a46=(a46-a54);
  a54=(a29*a46);
  a65=(a65-a54);
  a54=(a21*a46);
  a26=(a47*a11);
  a54=(a54-a26);
  a26=(a59*a54);
  a26=(a65-a26);
  a26=(a61*a26);
  a39=(a48*a39);
  a6=(a34*a6);
  a39=(a39+a6);
  a34=(a34*a31);
  a48=(a48*a14);
  a34=(a34+a48);
  a29=(a29*a34);
  a48=(a64*a11);
  a29=(a29+a48);
  a39=(a39-a29);
  a29=(a21*a39);
  a40=(a40*a12);
  a41=(a41*a51);
  a40=(a40+a41);
  a7=(a7*a31);
  a40=(a40+a7);
  a64=(a64*a46);
  a64=(a40+a64);
  a7=(a47*a64);
  a29=(a29-a7);
  a59=(a59*a34);
  a46=(a47*a46);
  a11=(a21*a11);
  a46=(a46+a11);
  a46=(a45*a46);
  a59=(a59+a46);
  a29=(a29-a59);
  a29=(a13*a29);
  a26=(a26-a29);
  a61=(a61*a54);
  a13=(a13*a34);
  a61=(a61-a13);
  a38=(a38*a61);
  a26=(a26-a38);
  if (res[0]!=0) res[0][6]=a26;
  if (res[0]!=0) res[0][7]=a0;
  a0=9.8705039999999994e-02;
  a24=(a24+a2);
  a0=(a0+a24);
  a35=casadi_sq(a35);
  a23=casadi_sq(a23);
  a35=(a35+a23);
  a43=(a43*a35);
  a0=(a0+a43);
  a37=casadi_sq(a37);
  a28=casadi_sq(a28);
  a37=(a37+a28);
  a53=(a53*a37);
  a0=(a0+a53);
  if (res[0]!=0) res[0][8]=a0;
  a63=(a47*a63);
  a67=(a21*a67);
  a63=(a63+a67);
  a58=(a45*a58);
  a63=(a63+a58);
  if (res[0]!=0) res[0][9]=a63;
  a19=(a47*a19);
  a20=(a21*a20);
  a19=(a19+a20);
  a17=(a45*a17);
  a19=(a19+a17);
  if (res[0]!=0) res[0][10]=a19;
  a42=(a47*a42);
  a32=(a21*a32);
  a42=(a42+a32);
  a49=(a45*a49);
  a42=(a42+a49);
  if (res[0]!=0) res[0][11]=a42;
  a30=(a47*a30);
  a25=(a21*a25);
  a30=(a30+a25);
  a55=(a45*a55);
  a30=(a30+a55);
  if (res[0]!=0) res[0][12]=a30;
  a47=(a47*a39);
  a21=(a21*a64);
  a47=(a47+a21);
  a45=(a45*a54);
  a47=(a47+a45);
  if (res[0]!=0) res[0][13]=a47;
  if (res[0]!=0) res[0][14]=a1;
  if (res[0]!=0) res[0][15]=a63;
  if (res[0]!=0) res[0][16]=a66;
  if (res[0]!=0) res[0][17]=a8;
  if (res[0]!=0) res[0][18]=a68;
  if (res[0]!=0) res[0][19]=a16;
  if (res[0]!=0) res[0][20]=a65;
  if (res[0]!=0) res[0][21]=a57;
  if (res[0]!=0) res[0][22]=a19;
  if (res[0]!=0) res[0][23]=a8;
  if (res[0]!=0) res[0][24]=a3;
  if (res[0]!=0) res[0][25]=a50;
  if (res[0]!=0) res[0][26]=a18;
  if (res[0]!=0) res[0][27]=a40;
  if (res[0]!=0) res[0][28]=a27;
  if (res[0]!=0) res[0][29]=a42;
  if (res[0]!=0) res[0][30]=a68;
  if (res[0]!=0) res[0][31]=a50;
  if (res[0]!=0) res[0][32]=a4;
  if (res[0]!=0) res[0][33]=a36;
  if (res[0]!=0) res[0][34]=a33;
  if (res[0]!=0) res[0][35]=a52;
  if (res[0]!=0) res[0][36]=a30;
  if (res[0]!=0) res[0][37]=a16;
  if (res[0]!=0) res[0][38]=a18;
  if (res[0]!=0) res[0][39]=a36;
  if (res[0]!=0) res[0][40]=a5;
  if (res[0]!=0) res[0][41]=a56;
  if (res[0]!=0) res[0][42]=a26;
  if (res[0]!=0) res[0][43]=a47;
  if (res[0]!=0) res[0][44]=a65;
  if (res[0]!=0) res[0][45]=a40;
  if (res[0]!=0) res[0][46]=a33;
  if (res[0]!=0) res[0][47]=a56;
  if (res[0]!=0) res[0][48]=a22;
  return 0;
}

CASADI_SYMBOL_EXPORT int M(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int M_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int M_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int M_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void M_release(int mem) {
}

CASADI_SYMBOL_EXPORT void M_incref(void) {
}

CASADI_SYMBOL_EXPORT void M_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int M_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int M_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real M_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* M_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* M_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int M_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int M_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 1*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
